/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package editorimg;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;

/**
 *
 * @author pc
 */
public class Vista extends javax.swing.JFrame {

     private BufferedImage imagenOriginal;
    private BufferedImage imagenProcesada;
    PanelImagen panelImagen = new PanelImagen();
    HiloGuardadoAutomatico hiloGuardadoAutomatico;
     private String efectoSeleccionado;
     private HiloProcesamientoImagen hiloProcesamiento;

    
    public Vista() {
        initComponents();
        efectoSeleccionado = "";
        imagenOriginal = null;
        imagenProcesada = null;
        this.setLocationRelativeTo(null);
         jPanel3.add(panelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 580, 310));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAddImg = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnNuevaImagen = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnGuardadoAutomatico = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        panelEfectos = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cmbEfecto = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("3ditorIMG");

        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/AddIMGicon (1).png"))); // NOI18N
        btnAddImg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddImgMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddImgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddImgMouseExited(evt);
            }
        });
        jPanel2.add(btnAddImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(153, 255, 153));
        jSeparator1.setForeground(new java.awt.Color(153, 255, 153));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 150, 10));

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccione un archivo:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        jLabel3.setFont(new java.awt.Font("Unispace", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("3ditorIMG");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel2, "card2");

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        btnNuevaImagen.setBackground(new java.awt.Color(51, 51, 51));
        btnNuevaImagen.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                btnNuevaImagenComponentRemoved(evt);
            }
        });
        btnNuevaImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevaImagenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevaImagenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevaImagenMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cargar nueva imagen");

        javax.swing.GroupLayout btnNuevaImagenLayout = new javax.swing.GroupLayout(btnNuevaImagen);
        btnNuevaImagen.setLayout(btnNuevaImagenLayout);
        btnNuevaImagenLayout.setHorizontalGroup(
            btnNuevaImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnNuevaImagenLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        btnNuevaImagenLayout.setVerticalGroup(
            btnNuevaImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnNuevaImagenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        btnGuardadoAutomatico.setBackground(new java.awt.Color(51, 51, 51));
        btnGuardadoAutomatico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardadoAutomaticoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardadoAutomaticoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardadoAutomaticoMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Activar autoguardado");

        javax.swing.GroupLayout btnGuardadoAutomaticoLayout = new javax.swing.GroupLayout(btnGuardadoAutomatico);
        btnGuardadoAutomatico.setLayout(btnGuardadoAutomaticoLayout);
        btnGuardadoAutomaticoLayout.setHorizontalGroup(
            btnGuardadoAutomaticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGuardadoAutomaticoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnGuardadoAutomaticoLayout.setVerticalGroup(
            btnGuardadoAutomaticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGuardadoAutomaticoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        btnSalir.setBackground(new java.awt.Color(51, 51, 51));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Salir");

        javax.swing.GroupLayout btnSalirLayout = new javax.swing.GroupLayout(btnSalir);
        btnSalir.setLayout(btnSalirLayout);
        btnSalirLayout.setHorizontalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnSalirLayout.setVerticalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        panelEfectos.setBackground(new java.awt.Color(51, 51, 51));
        panelEfectos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelEfectosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelEfectosMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Efectos:");

        cmbEfecto.setBackground(new java.awt.Color(102, 102, 102));
        cmbEfecto.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        cmbEfecto.setForeground(new java.awt.Color(255, 255, 255));
        cmbEfecto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blanco y negro", "Invertido", "Vintage" }));
        cmbEfecto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbEfectoItemStateChanged(evt);
            }
        });
        cmbEfecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEfectoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEfectosLayout = new javax.swing.GroupLayout(panelEfectos);
        panelEfectos.setLayout(panelEfectosLayout);
        panelEfectosLayout.setHorizontalGroup(
            panelEfectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEfectosLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEfectosLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(cmbEfecto, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        panelEfectosLayout.setVerticalGroup(
            panelEfectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEfectosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbEfecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnNuevaImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(panelEfectos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(btnGuardadoAutomatico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardadoAutomatico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevaImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(panelEfectos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 60));

        jPanel1.add(jPanel3, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public BufferedImage getImagenProcesada() {
        return imagenProcesada;
    }

    public void setImagenProcesada(BufferedImage imagenProcesada) {
        this.imagenProcesada = imagenProcesada;
    }

    public PanelImagen getPanelImagen() {
        return panelImagen;
    }

    public void actualizarPanelImagen() {
        panelImagen.setImagen(imagenProcesada);
        panelImagen.repaint();
    }
    
    private void btnAddImgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddImgMouseEntered
        btnAddImg.setBorder(BorderFactory.createLineBorder(Color.gray, 2));
    }//GEN-LAST:event_btnAddImgMouseEntered

    private void btnAddImgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddImgMouseExited
       btnAddImg.setBorder(null);
    }//GEN-LAST:event_btnAddImgMouseExited

    private void btnAddImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddImgMouseClicked
        
        JFileChooser fileChooser = new JFileChooser();
                int result = fileChooser.showOpenDialog(Vista.this);
                if (result == JFileChooser.APPROVE_OPTION) {
                    File selectedFile = fileChooser.getSelectedFile();
                    try {
                        BufferedImage imagen = ImageIO.read(selectedFile);
                        imagenOriginal = new BufferedImage(imagen.getWidth(), imagen.getHeight(), BufferedImage.TYPE_INT_RGB);
                        Graphics g = imagenOriginal.getGraphics();
                        g.drawImage(imagen, 0, 0, null);
                        g.dispose();

                        panelImagen.setImagen(imagenOriginal);
                        
                        //imagenProcesada = imagenOriginal;
                        
           CardLayout layout = (CardLayout) jPanel1.getLayout();
           layout.show(jPanel1, "card3");  
           
                    } catch (IOException ex) {
                        ex.printStackTrace();
                    }
                }
  
    }//GEN-LAST:event_btnAddImgMouseClicked

    private void btnNuevaImagenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaImagenMouseEntered
        btnNuevaImagen.setBackground(Color.gray);
    }//GEN-LAST:event_btnNuevaImagenMouseEntered

    private void btnNuevaImagenComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_btnNuevaImagenComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaImagenComponentRemoved

    private void btnNuevaImagenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaImagenMouseExited
        btnNuevaImagen.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_btnNuevaImagenMouseExited

    private void panelEfectosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEfectosMouseEntered
        //panelEfectos.setBackground(Color.gray);
    }//GEN-LAST:event_panelEfectosMouseEntered

    private void btnGuardadoAutomaticoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardadoAutomaticoMouseEntered
        btnGuardadoAutomatico.setBackground(Color.gray);
    }//GEN-LAST:event_btnGuardadoAutomaticoMouseEntered

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        btnSalir.setBackground(Color.gray);
    }//GEN-LAST:event_btnSalirMouseEntered

    private void panelEfectosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEfectosMouseExited
        //panelEfectos.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_panelEfectosMouseExited

    private void btnGuardadoAutomaticoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardadoAutomaticoMouseExited
        btnGuardadoAutomatico.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_btnGuardadoAutomaticoMouseExited

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        btnSalir.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_btnSalirMouseExited

    private void cmbEfectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEfectoActionPerformed
          efectoSeleccionado = String.valueOf(cmbEfecto.getSelectedItem());
                if (imagenOriginal != null) {
        
        if (hiloProcesamiento != null && hiloProcesamiento.isAlive()) {
            hiloProcesamiento.interrupt();
        }

        hiloProcesamiento = new HiloProcesamientoImagen(imagenOriginal, efectoSeleccionado, this);
        hiloProcesamiento.start();
    }
    }//GEN-LAST:event_cmbEfectoActionPerformed

    private void cmbEfectoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbEfectoItemStateChanged
       
                
    }//GEN-LAST:event_cmbEfectoItemStateChanged

    private void btnNuevaImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaImagenMouseClicked
        JFileChooser fileChooser = new JFileChooser();
                int result = fileChooser.showOpenDialog(Vista.this);
                if (result == JFileChooser.APPROVE_OPTION) {
                    File selectedFile = fileChooser.getSelectedFile();
                    try {
                        BufferedImage imagen = ImageIO.read(selectedFile);
                        imagenOriginal = new BufferedImage(imagen.getWidth(), imagen.getHeight(), BufferedImage.TYPE_INT_RGB);
                        Graphics g = imagenOriginal.getGraphics();
                        g.drawImage(imagen, 0, 0, null);
                        g.dispose();

                        panelImagen.setImagen(imagenOriginal);
                        
                        //imagenProcesada = imagenOriginal;
                         
                    } catch (IOException ex) {
                        ex.printStackTrace();
                    }
                }
    }//GEN-LAST:event_btnNuevaImagenMouseClicked

    private void btnGuardadoAutomaticoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardadoAutomaticoMouseClicked
        hiloGuardadoAutomatico = new HiloGuardadoAutomatico(imagenProcesada, this);
        hiloGuardadoAutomatico.start();
        jLabel1.setText("Autoguardado activo");
    }//GEN-LAST:event_btnGuardadoAutomaticoMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAddImg;
    private javax.swing.JPanel btnGuardadoAutomatico;
    private javax.swing.JPanel btnNuevaImagen;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JComboBox<String> cmbEfecto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelEfectos;
    // End of variables declaration//GEN-END:variables
}
